# Generated by Django 3.1 on 2022-08-24 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_variation'),
        ('carts', '0002_auto_20220824_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='bookstore.Variation'),
        ),
    ]
