# Generated by Django 3.1 on 2022-09-18 12:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookloan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
