# Generated by Django 3.1 on 2022-09-18 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookloan', '0002_auto_20220918_1825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookloanbook',
            name='edition',
        ),
        migrations.RemoveField(
            model_name='bookloanbook',
            name='type',
        ),
        migrations.AddField(
            model_name='bookloanbook',
            name='bookloandone',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bookloan',
            name='return_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
