# Generated by Django 3.1 on 2022-09-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookloan', '0004_auto_20220918_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='return_date',
            field=models.DateTimeField(blank=True),
        ),
    ]
