# Generated by Django 3.1 on 2022-09-19 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookloan', '0006_bookloan_remaining_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookloan',
            name='late_charge',
            field=models.IntegerField(default=False),
        ),
    ]
