# Generated by Django 3.1 on 2022-09-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookloan', '0008_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookloan',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
