# Generated by Django 3.1 on 2022-09-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookloan', '0009_bookloan_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookloan',
            name='actual_return_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='bookloan',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
